version: "3.1"
services:
  db_alfinfernandhapratama_betest:
    build: 
      context: ./
      dockerfile: mongo.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - mynetwork

  redis_alfinfernandhapratama_betest:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6380:6379"
    networks:
      - mynetwork

  ms-alfinfernandhapratamabetest:
    build: 
      context: ./
      dockerfile: app.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge