version: "3.1"
services:
  mongo:
    build: ./mongodb-rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: yasfin
      MONGO_INITDB_DATABASE: db_alfinfernandhapratama_betest
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: "27017"
    ports:
      - 27017:27017

